[env]
TERM = "xterm-256color"

[shell]
program = "zellij"
args = ["a", "Office"]

[window]
dimensions = { columns = 180, lines = 54 }
padding.x = 8
padding.y = 6
decorations = "None"
opacity = 0.97


[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
