[env]
TERM = "xterm-256color"

[shell]
program = "zellij"
args = ["a", "Office"]

[window]
dimensions = { columns = 160, lines = 40 }
padding.x = 16
padding.y = 14
decorations = "None"
opacity = 0.97


[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
